### ISSUE TITLE
Tom needs to read reviews

### ISSUE THREAD

**Issue by olehermanse** [cf-bottom/self#19]
Right now, tom doesn't see reviews (in API they are separate from comments) so he will ask for reviews even if PR has been reviewed.

**Comment by olehermanse** [comment]
@oleorhagen this should be fixed before enabling for all mender repos.

**Comment by oleorhagen** [comment]
https://github.com/cf-bottom/self/pull/24

**Comment by vpodzime** [comment]
Resolved by #24.
