### ISSUE TITLE
Approve PRs that meet minimum requirements from repository

### ISSUE THREAD

**Issue by nickanderson** [cf-bottom/self#52]
It would be nice if our various automated tests could function as an approval.

For example, in CFEngine core we run Travis, and we can request Jenkins builds (with options for the difficulty of the jenkins gauntlent like exotics and deployment tests). It would be nice if tom would approve a PR (allowing merge) if both travis and Jenkins were green.

**Comment by olehermanse** [comment]
GitHub has required status checks, I think maybe it's better to use that system?

**Comment by vpodzime** [comment]
Yeah, traffic lights differ from approvals.

**Comment by nickanderson** [comment]
? my thought was more about being able to jump the human review queue for changes that pass some relatively high bar dunno how status checks work in combination with required reviews. required status checks would just raise our bar further, which is also probably ok, just not what I was after.

**Comment by nickanderson** [comment]
I had this thoguht when I introduced a new example in core over the weekend and was facing having to wait days for a human reviewer. @Lex-2008 saved me from pergatory though.

**Comment by olehermanse** [comment]
@nickanderson The reason for the required approval is that we want code to be reviewed (by humans). Making tom bypass that would defeat the purpose. (Also, you are an admin and can disable the required review in settings, if you really need to).
